# Generated by Django 5.1.2 on 2024-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=2748395050, unique=True),
        ),
    ]
