# Generated by Django 5.1.2 on 2024-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0011_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=1179121584, unique=True),
        ),
    ]
