# Generated by Django 5.1.2 on 2024-11-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=1058360984, unique=True),
        ),
    ]
