# Generated by Django 5.1.3 on 2024-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0025_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=21076964944654, unique=True),
        ),
    ]
