# Generated by Django 5.1.3 on 2024-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0027_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=16300597815625, unique=True),
        ),
    ]
