# Generated by Django 5.1.3 on 2024-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0049_alter_notice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='code',
            field=models.PositiveBigIntegerField(default=10421111883780, unique=True),
        ),
    ]
