# Generated by Django 5.1.2 on 2024-10-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='fond',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helper.fond'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=4274221940, editable=False),
        ),
    ]
