# Generated by Django 5.1.2 on 2024-10-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_information_fond_alter_information_single_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=3212734908, editable=False),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.TimeField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seraial', to='main.information')),
            ],
        ),
    ]
