# Generated by Django 5.1.2 on 2024-10-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('main', '0003_alter_information_single_code_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employeeuser'),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=1853397164, editable=False),
        ),
    ]
