# Generated by Django 5.1.2 on 2024-11-06 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_information_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='date',
        ),
        migrations.AddField(
            model_name='information',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message="Kunni tug'ri kiriting?"), django.core.validators.MaxValueValidator(31, message="Kunni tug'ri kiriting?")]),
        ),
        migrations.AddField(
            model_name='information',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message="Oyni tug'ri kiriting?"), django.core.validators.MaxValueValidator(12, message="Oyni tug'ri kiriting?")]),
        ),
        migrations.AddField(
            model_name='information',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1920, message="Yilni tug'ri kiriting?"), django.core.validators.MaxValueValidator(2024, message="Yilni tug'ri kiriting?")]),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=1570016632, editable=False),
        ),
    ]
