# Generated by Django 5.1.2 on 2024-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_information_date_information_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='fond',
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=1360433381, editable=False),
        ),
    ]
