# Generated by Django 5.1.2 on 2024-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_information_fond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=2400489815, editable=False),
        ),
    ]
