# Generated by Django 5.1.2 on 2024-11-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_information_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=4260951667, editable=False),
        ),
    ]
