# Generated by Django 5.1.2 on 2024-11-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_remove_category_is_child'),
        ('main', '0015_alter_information_single_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='part',
        ),
        migrations.AddField(
            model_name='information',
            name='fond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.fond'),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=2283972106, editable=False),
        ),
    ]
