# Generated by Django 5.1.2 on 2024-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_information_part_information_fond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='color',
            field=models.CharField(choices=[('coloured', 'coloured'), ('white-black', 'white-black')], default='coloured', max_length=12),
        ),
        migrations.AlterField(
            model_name='information',
            name='location_on_server',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=2559719154, editable=False),
        ),
    ]
