# Generated by Django 5.1.2 on 2024-11-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_remove_category_is_child'),
        ('main', '0017_alter_information_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='format',
            field=models.ManyToManyField(blank=True, null=True, related_name='format', to='helper.format'),
        ),
        migrations.AlterField(
            model_name='information',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, related_name='language', to='helper.language'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mtv',
            field=models.ManyToManyField(blank=True, null=True, related_name='mtv', to='helper.mtv'),
        ),
        migrations.AlterField(
            model_name='information',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, related_name='region', to='helper.region'),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=3281081971, editable=False),
        ),
        migrations.AlterField(
            model_name='serial',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='main.information'),
        ),
    ]
