# Generated by Django 5.0.7 on 2024-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_information_single_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='location_on_server',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='mtv_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=7163245383, editable=False),
        ),
    ]
