# Generated by Django 5.0.7 on 2024-11-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_information_single_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='color',
            field=models.CharField(choices=[('coloured', 'coloured'), ('whiteblack', 'whiteblack')], default='coloured', max_length=12),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=2946304477, editable=False),
        ),
    ]
