# Generated by Django 5.0.7 on 2024-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_information_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='color',
            field=models.CharField(choices=[('coloured', 'coloured'), ('white-black', 'white-black')], default='coloured', max_length=12),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=1609953083, editable=False),
        ),
    ]
