# Generated by Django 5.1.3 on 2024-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_information_single_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['part']},
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=19947831385796, editable=False),
        ),
    ]
