# Generated by Django 5.1.3 on 2024-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_information_single_code_alter_serial_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=17837032280822, editable=False),
        ),
    ]
