# Generated by Django 5.1.3 on 2024-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_information_brief_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='brief_data',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=52873554137965, editable=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='summary',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
