# Generated by Django 5.1.3 on 2024-12-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_information_single_code_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['created'], 'permissions': [('can_confidential', 'Can confidential information')]},
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=12367001532631, editable=False),
        ),
    ]
