# Generated by Django 5.1.3 on 2024-12-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_information_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': [('can_confidential', 'Can confidential information')]},
        ),
        migrations.AlterField(
            model_name='information',
            name='single_code',
            field=models.PositiveBigIntegerField(default=19210353785072, editable=False),
        ),
    ]
