# Generated by Django 5.1.3 on 2024-12-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_created_at_rating_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='single_code',
        ),
    ]
