# Generated by Django 5.1.3 on 2024-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_information_single_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='restorat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
