# Generated by Django 5.1.2 on 2024-10-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('EMPLOYEE', 'EMPLOYEE'), ('LOW_USER', 'LOW_USER')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
