# Generated by Django 5.1.3 on 2024-12-04 11:55

import utils.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('EMPLOYEE', 'EMPLOYEE'), ('LOW_USER', 'LOW_USER')], default=utils.choices.UserRoleEnum['LOW_USER'], max_length=20),
        ),
    ]
