# Generated by Django 5.1.3 on 2024-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('EMPLOYEE', 'EMPLOYEE'), ('LOW_USER', 'LOW_USER')], default='LOW_USER', max_length=10),
        ),
    ]
