# Generated by Django 5.1.2 on 2024-11-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_alter_category_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
