# Generated by Django 5.1.2 on 2024-11-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_category_is_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_child',
        ),
    ]
